FROM nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu20.04

RUN apt update && \
    apt install -y \
        python3 \
        python3-pip \
        build-essential \
        libgl1


#RUN python3.6 -m pip install -U --force-reinstall pip
RUN pip3 install torch torchvision torchaudio

RUN pip3 install 'opencv-python<4.6'
#RUN pip3 install onnxruntime

RUN pip3 install --upgrade pip
RUN pip3 install nvidia-pyindex nvidia-tensorrt
RUN pip3 install onnxruntime-gpu
RUN pip3 install seaborn


ARG DEBIAN_FRONTEND=noninteractive
RUN apt install -y libglib2.0-0
RUN apt install -y imagemagick
RUN apt install -y python3-tk git sudo  pkg-config cmake
