FROM ubuntu:bionic-20230126

RUN apt update && \
    apt install -y python3.6 python3-pip python3.6-dev build-essential


RUN python3.6 -m pip install -U --force-reinstall pip
RUN pip3 install torch torchvision torchaudio

RUN pip3 install onnxruntime seaborn
RUN pip3 install 'opencv-python<4.6'

